json.id bed.id
json.yard_id bed.yard_id
json.name bed.name
json.attached_to_house bed.attached_to_house
json.orientation bed.orientation
json.width bed.width
json.depth bed.depth
json.sunlight_morning bed.sunlight_morning
json.sunlight_afternoon bed.sunlight_afternoon
json.watered bed.watered
json.template_id bed.template_id
json.template_placements bed.template_placements